version: '3.7'

services:

  ts-backend2.0:
    container_name: backend2.0
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '0.0.0.0:8080:8080'
    environment:
      - CHOKIDAR_USEPOLLING=true
